language: python
python:
  - "3.6"
services: 
  - mysql
env: 
  -DJANGO=2.2 DB=mysql
install: 
  - pip install -r requirements.txt
before_script: 
  echo before_script
script:
  - python ./practice-app/manage.py test